package com.drivers.test.repository

class Localizer {
    val langLabels = mapOf("en" to "EN", "ja" to "日本語", "es" to "ES", "fr" to "FR")

    private val translations: Map<String, Map<String, String>> = mapOf(
        "en" to mapOf(
            "appTitle" to "Driver's Test Practice",
            "selectStateDesc" to "Choose your state to start practicing",
            "questionsAvailable" to "{count} questions",
            "comingSoon" to "Coming soon",
            "title" to "{state} Driver's Test",
            "subtitle" to "Practice for your {state_name} {agency} written test.",
            "quizzes" to "Quizzes",
            "avgScore" to "Avg Score",
            "passStreak" to "Pass Streak",
            "viewStats" to "View Stats",
            "modeRandom" to "Random",
            "modeRandomDesc" to "All questions",
            "modeWeak" to "Weak Spots",
            "modeWeakDesc" to "Most missed",
            "numQuestions" to "Number of questions:",
            "startQuiz" to "Start Quiz",
            "noWeakSpots" to "No weak spots yet",
            "next" to "Next",
            "seeResults" to "See Results",
            "missed" to "Missed",
            "congratulations" to "Congratulations!",
            "keepPracticing" to "Keep Practicing!",
            "resultDetail" to
                "You got {correct} out of {total} correct. You need {pass_pct}% to pass the actual {agency} test.",
            "newQuiz" to "New Quiz",
            "reviewMissed" to "Review Missed Questions ({count})",
            "perfectScore" to "Perfect Score!",
            "perfectMsg" to "You answered every question correctly.",
            "yourAnswer" to "Your answer",
            "correct" to "Correct",
            "back" to "Back",
            "changeState" to "Change State",
            "yourProgress" to "Your Progress",
            "qsSeen" to "Q's Seen",
            "bestScore" to "Best Score",
            "scoreHistory" to "Score History",
            "accuracyByCategory" to "Accuracy by Category",
            "mostMissed" to "Most Missed Questions",
            "resetAll" to "Reset All Progress",
            "resetConfirm" to "This will erase all your quiz history and question tracking for {state_name}. Continue?",
            "pass" to "PASS",
            "fail" to "FAIL",
            "passingScore" to "Real test: {test_count} questions, {pass_count} correct to pass ({pass_pct}%)",
            "statsEmpty" to "Take a quiz to see your progress",
            "statsOneMore" to "Take one more quiz to see the chart",
            "cancel" to "Cancel",
            "resetButton" to "Reset",
            "all" to "All",
        ),
        "ja" to mapOf(
            "appTitle" to "運転免許テスト練習",
            "selectStateDesc" to "練習を開始するには州を選んでください",
            "questionsAvailable" to "{count}問",
            "comingSoon" to "準備中",
            "title" to "{state} 運転免許テスト",
            "subtitle" to "{state_name} {agency}の筆記試験対策。",
            "quizzes" to "テスト回数",
            "avgScore" to "平均点",
            "passStreak" to "連続合格",
            "viewStats" to "統計を見る",
            "modeRandom" to "ランダム",
            "modeRandomDesc" to "全問題",
            "modeWeak" to "弱点",
            "modeWeakDesc" to "よく間違える問題",
            "numQuestions" to "問題数：",
            "startQuiz" to "テスト開始",
            "noWeakSpots" to "弱点はまだありません",
            "next" to "次へ",
            "seeResults" to "結果を見る",
            "missed" to "不正解率",
            "congratulations" to "おめでとうございます！",
            "keepPracticing" to "もっと練習しましょう！",
            "resultDetail" to "{total}問中{correct}問正解です。{agency}試験の合格ラインは{pass_pct}%です。",
            "newQuiz" to "新しいテスト",
            "reviewMissed" to "間違えた問題を復習 ({count})",
            "perfectScore" to "満点！",
            "perfectMsg" to "すべての問題に正解しました。",
            "yourAnswer" to "あなたの回答",
            "correct" to "正解",
            "back" to "戻る",
            "changeState" to "州を変更",
            "yourProgress" to "あなたの成績",
            "qsSeen" to "出題済み",
            "bestScore" to "最高点",
            "scoreHistory" to "スコア推移",
            "accuracyByCategory" to "カテゴリー別正答率",
            "mostMissed" to "最もよく間違える問題",
            "resetAll" to "すべての記録をリセット",
            "resetConfirm" to "{state_name}のすべてのテスト履歴と問題追跡データが消去されます。よろしいですか？",
            "pass" to "合格",
            "fail" to "不合格",
            "passingScore" to "本番: {test_count}問中{pass_count}問正解で合格 ({pass_pct}%)",
            "statsEmpty" to "クイズを受けて進捗を確認しましょう",
            "statsOneMore" to "もう1つクイズを受けてグラフを見ましょう",
            "cancel" to "キャンセル",
            "resetButton" to "リセット",
            "all" to "全て",
        ),
        "es" to mapOf(
            "appTitle" to "Práctica de Examen de Conducir",
            "selectStateDesc" to "Elige tu estado para empezar a practicar",
            "questionsAvailable" to "{count} preguntas",
            "comingSoon" to "Próximamente",
            "title" to "Examen de Conducir {state}",
            "subtitle" to "Practica para el examen escrito del {agency} de {state_name}.",
            "quizzes" to "Pruebas",
            "avgScore" to "Promedio",
            "passStreak" to "Racha",
            "viewStats" to "Ver Estadísticas",
            "modeRandom" to "Aleatorio",
            "modeRandomDesc" to "Todas las preguntas",
            "modeWeak" to "Puntos Débiles",
            "modeWeakDesc" to "Más falladas",
            "numQuestions" to "Número de preguntas:",
            "startQuiz" to "Comenzar",
            "noWeakSpots" to "Sin puntos débiles aún",
            "next" to "Siguiente",
            "seeResults" to "Ver Resultados",
            "missed" to "Fallada",
            "congratulations" to "¡Felicidades!",
            "keepPracticing" to "¡Sigue Practicando!",
            "resultDetail" to
                "Acertaste {correct} de {total}. Necesitas {pass_pct}% para aprobar el examen del {agency}.",
            "newQuiz" to "Nuevo Examen",
            "reviewMissed" to "Revisar Preguntas Falladas ({count})",
            "perfectScore" to "¡Puntuación Perfecta!",
            "perfectMsg" to "Respondiste correctamente todas las preguntas.",
            "yourAnswer" to "Tu respuesta",
            "correct" to "Correcta",
            "back" to "Volver",
            "changeState" to "Cambiar Estado",
            "yourProgress" to "Tu Progreso",
            "qsSeen" to "Vistas",
            "bestScore" to "Mejor",
            "scoreHistory" to "Historial de Puntuación",
            "accuracyByCategory" to "Precisión por Categoría",
            "mostMissed" to "Preguntas Más Falladas",
            "resetAll" to "Borrar Todo el Progreso",
            "resetConfirm" to "Esto borrará todo tu historial y seguimiento de {state_name}. ¿Continuar?",
            "pass" to "APROBADO",
            "fail" to "REPROBADO",
            "passingScore" to "Examen real: {test_count} preguntas, {pass_count} correctas para aprobar ({pass_pct}%)",
            "statsEmpty" to "Toma un examen para ver tu progreso",
            "statsOneMore" to "Toma un examen más para ver el gráfico",
            "cancel" to "Cancelar",
            "resetButton" to "Restablecer",
            "all" to "Todos",
        ),
        "fr" to mapOf(
            "appTitle" to "Pratique d'examen de conduite",
            "selectStateDesc" to "Choisissez votre province pour commencer",
            "questionsAvailable" to "{count} questions",
            "comingSoon" to "Bientôt disponible",
            "title" to "Examen de conduite {state}",
            "subtitle" to "Pratiquez pour l'examen écrit de {state_name}.",
            "quizzes" to "Tests",
            "avgScore" to "Moyenne",
            "passStreak" to "Série",
            "viewStats" to "Voir les stats",
            "modeRandom" to "Aléatoire",
            "modeRandomDesc" to "Toutes les questions",
            "modeWeak" to "Points faibles",
            "modeWeakDesc" to "Les plus ratées",
            "numQuestions" to "Nombre de questions :",
            "startQuiz" to "Commencer",
            "noWeakSpots" to "Aucun point faible",
            "next" to "Suivant",
            "seeResults" to "Voir les résultats",
            "missed" to "Ratée",
            "congratulations" to "Félicitations !",
            "keepPracticing" to "Continuez à pratiquer !",
            "resultDetail" to "Vous avez obtenu {correct} sur {total}. Il faut {pass_pct}% pour réussir l'examen.",
            "newQuiz" to "Nouveau test",
            "reviewMissed" to "Revoir les erreurs ({count})",
            "perfectScore" to "Score parfait !",
            "perfectMsg" to "Vous avez répondu correctement à toutes les questions.",
            "yourAnswer" to "Votre réponse",
            "correct" to "Correcte",
            "back" to "Retour",
            "changeState" to "Changer de province",
            "yourProgress" to "Votre progrès",
            "qsSeen" to "Vues",
            "bestScore" to "Meilleur",
            "scoreHistory" to "Historique des scores",
            "accuracyByCategory" to "Précision par catégorie",
            "mostMissed" to "Questions les plus ratées",
            "resetAll" to "Effacer tout le progrès",
            "resetConfirm" to "Cela effacera tout votre historique pour {state_name}. Continuer ?",
            "pass" to "RÉUSSI",
            "fail" to "ÉCHOUÉ",
            "passingScore" to
                "Examen réel : {test_count} questions, {pass_count} bonnes réponses pour réussir ({pass_pct}%)",
            "statsEmpty" to "Passez un quiz pour voir votre progression",
            "statsOneMore" to "Passez un quiz de plus pour voir le graphique",
            "cancel" to "Annuler",
            "resetButton" to "Réinitialiser",
            "all" to "Tout",
        ),
    )

    fun t(
        key: String,
        lang: String,
        vars: Map<String, String> = emptyMap(),
    ): String {
        var s = translations[lang]?.get(key) ?: translations["en"]?.get(key) ?: key
        for ((k, v) in vars) {
            s = s.replace("{$k}", v)
        }
        return s
    }
}
