package com.drivers.test.repository

class Localizer {
    val langLabels = mapOf("en" to "EN", "ja" to "日本語", "es" to "ES")

    private val translations: Map<String, Map<String, String>> = mapOf(
        "en" to mapOf(
            "appTitle" to "Driver's Test Practice",
            "selectStateDesc" to "Choose your state to start practicing",
            "questionsAvailable" to "{count} questions",
            "comingSoon" to "Coming soon",
            "title" to "{state} Driver's Test",
            "subtitle" to "Practice for your {state_name} {agency} written test.",
            "quizzes" to "Quizzes",
            "avgScore" to "Avg Score",
            "passStreak" to "Pass Streak",
            "viewStats" to "View Stats",
            "modeRandom" to "Random",
            "modeRandomDesc" to "All questions",
            "modeWeak" to "Weak Spots",
            "modeWeakDesc" to "Most missed",
            "numQuestions" to "Number of questions:",
            "startQuiz" to "Start Quiz",
            "noWeakSpots" to "No weak spots yet",
            "next" to "Next",
            "seeResults" to "See Results",
            "missed" to "Missed",
            "congratulations" to "Congratulations!",
            "keepPracticing" to "Keep Practicing!",
            "resultDetail" to "You got {correct} out of {total} correct. You need {pass_pct}% to pass the actual {agency} test.",
            "newQuiz" to "New Quiz",
            "reviewMissed" to "Review Missed Questions ({count})",
            "perfectScore" to "Perfect Score!",
            "perfectMsg" to "You answered every question correctly.",
            "yourAnswer" to "Your answer",
            "correct" to "Correct",
            "back" to "Back",
            "changeState" to "Change State",
            "yourProgress" to "Your Progress",
            "qsSeen" to "Q's Seen",
            "bestScore" to "Best Score",
            "scoreHistory" to "Score History",
            "accuracyByCategory" to "Accuracy by Category",
            "mostMissed" to "Most Missed Questions",
            "resetAll" to "Reset All Progress",
            "resetConfirm" to "This will erase all your quiz history and question tracking for {state_name}. Continue?",
            "pass" to "PASS",
            "fail" to "FAIL",
            "passingScore" to "Passing: {pass_pct}% ({pass_count}/{test_count})",
        ),
        "ja" to mapOf(
            "appTitle" to "運転免許テスト練習",
            "selectStateDesc" to "練習を開始するには州を選んでください",
            "questionsAvailable" to "{count}問",
            "comingSoon" to "準備中",
            "title" to "{state} 運転免許テスト",
            "subtitle" to "{state_name} {agency}の筆記試験対策。",
            "quizzes" to "テスト回数",
            "avgScore" to "平均点",
            "passStreak" to "連続合格",
            "viewStats" to "統計を見る",
            "modeRandom" to "ランダム",
            "modeRandomDesc" to "全問題",
            "modeWeak" to "弱点",
            "modeWeakDesc" to "よく間違える問題",
            "numQuestions" to "問題数：",
            "startQuiz" to "テスト開始",
            "noWeakSpots" to "弱点はまだありません",
            "next" to "次へ",
            "seeResults" to "結果を見る",
            "missed" to "不正解率",
            "congratulations" to "おめでとうございます！",
            "keepPracticing" to "もっと練習しましょう！",
            "resultDetail" to "{total}問中{correct}問正解です。{agency}試験の合格ラインは{pass_pct}%です。",
            "newQuiz" to "新しいテスト",
            "reviewMissed" to "間違えた問題を復習 ({count})",
            "perfectScore" to "満点！",
            "perfectMsg" to "すべての問題に正解しました。",
            "yourAnswer" to "あなたの回答",
            "correct" to "正解",
            "back" to "戻る",
            "changeState" to "州を変更",
            "yourProgress" to "あなたの成績",
            "qsSeen" to "出題済み",
            "bestScore" to "最高点",
            "scoreHistory" to "スコア推移",
            "accuracyByCategory" to "カテゴリー別正答率",
            "mostMissed" to "最もよく間違える問題",
            "resetAll" to "すべての記録をリセット",
            "resetConfirm" to "{state_name}のすべてのテスト履歴と問題追跡データが消去されます。よろしいですか？",
            "pass" to "合格",
            "fail" to "不合格",
            "passingScore" to "合格ライン: {pass_pct}% ({pass_count}/{test_count})",
        ),
        "es" to mapOf(
            "appTitle" to "Práctica de Examen de Conducir",
            "selectStateDesc" to "Elige tu estado para empezar a practicar",
            "questionsAvailable" to "{count} preguntas",
            "comingSoon" to "Próximamente",
            "title" to "Examen de Conducir {state}",
            "subtitle" to "Practica para el examen escrito del {agency} de {state_name}.",
            "quizzes" to "Pruebas",
            "avgScore" to "Promedio",
            "passStreak" to "Racha",
            "viewStats" to "Ver Estadísticas",
            "modeRandom" to "Aleatorio",
            "modeRandomDesc" to "Todas las preguntas",
            "modeWeak" to "Puntos Débiles",
            "modeWeakDesc" to "Más falladas",
            "numQuestions" to "Número de preguntas:",
            "startQuiz" to "Comenzar",
            "noWeakSpots" to "Sin puntos débiles aún",
            "next" to "Siguiente",
            "seeResults" to "Ver Resultados",
            "missed" to "Fallada",
            "congratulations" to "¡Felicidades!",
            "keepPracticing" to "¡Sigue Practicando!",
            "resultDetail" to "Acertaste {correct} de {total}. Necesitas {pass_pct}% para aprobar el examen del {agency}.",
            "newQuiz" to "Nuevo Examen",
            "reviewMissed" to "Revisar Preguntas Falladas ({count})",
            "perfectScore" to "¡Puntuación Perfecta!",
            "perfectMsg" to "Respondiste correctamente todas las preguntas.",
            "yourAnswer" to "Tu respuesta",
            "correct" to "Correcta",
            "back" to "Volver",
            "changeState" to "Cambiar Estado",
            "yourProgress" to "Tu Progreso",
            "qsSeen" to "Vistas",
            "bestScore" to "Mejor",
            "scoreHistory" to "Historial de Puntuación",
            "accuracyByCategory" to "Precisión por Categoría",
            "mostMissed" to "Preguntas Más Falladas",
            "resetAll" to "Borrar Todo el Progreso",
            "resetConfirm" to "Esto borrará todo tu historial y seguimiento de {state_name}. ¿Continuar?",
            "pass" to "APROBADO",
            "fail" to "REPROBADO",
            "passingScore" to "Aprobación: {pass_pct}% ({pass_count}/{test_count})",
        ),
    )

    fun t(key: String, lang: String, vars: Map<String, String> = emptyMap()): String {
        var s = translations[lang]?.get(key) ?: translations["en"]?.get(key) ?: key
        for ((k, v) in vars) {
            s = s.replace("{$k}", v)
        }
        return s
    }
}
