package com.drivers.test.repository

class Localizer {
    val langLabels = mapOf("en" to "EN", "ja" to "日本語", "es" to "ES", "fr" to "FR")

    private val translations: Map<String, Map<String, String>> = mapOf(
        "en" to mapOf(
            "appTitle" to "Driver's Test Practice",
            "selectStateDesc" to "Choose your state to start practicing",
            "questionsAvailable" to "{count} questions",
            "comingSoon" to "Coming soon",
            "title" to "{state} Driver's Test",
            "subtitle" to "Practice for your {state_name} {agency} written test.",
            "quizzes" to "Quizzes",
            "avgScore" to "Avg Score",
            "passStreak" to "Pass Streak",
            "viewStats" to "View Stats",
            "modeRandom" to "Random",
            "modeRandomDesc" to "All questions",
            "modeWeak" to "Weak Spots",
            "modeWeakDesc" to "Most missed",
            "numQuestions" to "Number of questions:",
            "startQuiz" to "Start Quiz",
            "noWeakSpots" to "No weak spots yet",
            "next" to "Next",
            "seeResults" to "See Results",
            "missed" to "Missed",
            "congratulations" to "Congratulations!",
            "keepPracticing" to "Keep Practicing!",
            "resultDetail" to
                "You got {correct} out of {total} correct. You need {pass_pct}% to pass the actual {agency} test.",
            "newQuiz" to "New Quiz",
            "reviewMissed" to "Review Missed Questions ({count})",
            "perfectScore" to "Perfect Score!",
            "perfectMsg" to "You answered every question correctly.",
            "yourAnswer" to "Your answer",
            "correct" to "Correct",
            "back" to "Back",
            "changeState" to "Change State",
            "yourProgress" to "Your Progress",
            "qsSeen" to "Q's Seen",
            "bestScore" to "Best Score",
            "scoreHistory" to "Score History",
            "accuracyByCategory" to "Accuracy by Category",
            "mostMissed" to "Most Missed Questions",
            "resetAll" to "Reset All Progress",
            "resetConfirm" to "This will erase all your quiz history and question tracking for {state_name}. Continue?",
            "pass" to "PASS",
            "fail" to "FAIL",
            "passingScore" to "Real test: {test_count} questions, {pass_count} correct to pass ({pass_pct}%)",
            "statsEmpty" to "Take a quiz to see your progress",
            "statsOneMore" to "Take one more quiz to see the chart",
            "cancel" to "Cancel",
            "resetButton" to "Reset",
            "all" to "All",
            "aboutThisTest" to "About this test",
            "sourceLabel" to "Source",
            "editionLabel" to "Edition",
            "fromManual" to "From the manual",
            "fromManualEnNote" to "",
            "cat_license_system" to "License System",
            "cat_driver_testing" to "Driver Testing",
            "cat_driver_responsibility" to "Driver Responsibility",
            "cat_safe_driving_rules" to "Safe Driving Rules",
            "cat_defensive_driving" to "Defensive Driving",
            "cat_alcohol_drugs_health" to "Alcohol, Drugs & Health",
            "cat_penalties_and_points" to "Penalties & Points",
            "cat_sharing_the_road" to "Sharing the Road",
            "cat_vehicle_information" to "Vehicle Information",
            "cat_signs_and_signals" to "Signs & Signals",
            "gradeLabel" to "Grade",
            "fidelityLabel" to "fidelity",
            "coverageLabel" to "coverage",
            "officialTestLangsLabel" to "Official test languages",
            "officialTestCaption" to "✓ = offered on the official {agency} test — others practice-only",
            "officialTestLangsAndOthers" to "and others",
            "officialTestLangsUnknown" to "Not stated in the manual — check with {agency}",
            "officialTestPracticeNote" to
                "This app also lets you practice in languages not offered on the official test.",
        ),
        "ja" to mapOf(
            "appTitle" to "運転免許テスト練習",
            "selectStateDesc" to "練習を開始するには州を選んでください",
            "questionsAvailable" to "{count}問",
            "comingSoon" to "準備中",
            "title" to "{state} 運転免許テスト",
            "subtitle" to "{state_name} {agency}の筆記試験対策。",
            "quizzes" to "テスト回数",
            "avgScore" to "平均点",
            "passStreak" to "連続合格",
            "viewStats" to "統計を見る",
            "modeRandom" to "ランダム",
            "modeRandomDesc" to "全問題",
            "modeWeak" to "弱点",
            "modeWeakDesc" to "よく間違える問題",
            "numQuestions" to "問題数：",
            "startQuiz" to "テスト開始",
            "noWeakSpots" to "弱点はまだありません",
            "next" to "次へ",
            "seeResults" to "結果を見る",
            "missed" to "不正解率",
            "congratulations" to "おめでとうございます！",
            "keepPracticing" to "もっと練習しましょう！",
            "resultDetail" to "{total}問中{correct}問正解です。{agency}試験の合格ラインは{pass_pct}%です。",
            "newQuiz" to "新しいテスト",
            "reviewMissed" to "間違えた問題を復習 ({count})",
            "perfectScore" to "満点！",
            "perfectMsg" to "すべての問題に正解しました。",
            "yourAnswer" to "あなたの回答",
            "correct" to "正解",
            "back" to "戻る",
            "changeState" to "州を変更",
            "yourProgress" to "あなたの成績",
            "qsSeen" to "出題済み",
            "bestScore" to "最高点",
            "scoreHistory" to "スコア推移",
            "accuracyByCategory" to "カテゴリー別正答率",
            "mostMissed" to "最もよく間違える問題",
            "resetAll" to "すべての記録をリセット",
            "resetConfirm" to "{state_name}のすべてのテスト履歴と問題追跡データが消去されます。よろしいですか？",
            "pass" to "合格",
            "fail" to "不合格",
            "passingScore" to "本番: {test_count}問中{pass_count}問正解で合格 ({pass_pct}%)",
            "statsEmpty" to "クイズを受けて進捗を確認しましょう",
            "statsOneMore" to "もう1つクイズを受けてグラフを見ましょう",
            "cancel" to "キャンセル",
            "resetButton" to "リセット",
            "all" to "全て",
            "aboutThisTest" to "このテストについて",
            "sourceLabel" to "出典",
            "editionLabel" to "版",
            "fromManual" to "マニュアルより",
            "fromManualEnNote" to "（英語）",
            "cat_license_system" to "免許制度",
            "cat_driver_testing" to "運転試験",
            "cat_driver_responsibility" to "運転者の責任",
            "cat_safe_driving_rules" to "安全運転のルール",
            "cat_defensive_driving" to "防御運転",
            "cat_alcohol_drugs_health" to "飲酒・薬物・健康",
            "cat_penalties_and_points" to "罰則と点数",
            "cat_sharing_the_road" to "道路の共有",
            "cat_vehicle_information" to "車両情報",
            "cat_signs_and_signals" to "標識と信号",
            "gradeLabel" to "評価",
            "fidelityLabel" to "忠実度",
            "coverageLabel" to "カバー率",
            "officialTestLangsLabel" to "公式テスト言語",
            "officialTestCaption" to "✓ = {agency}公式テストで利用可能 — その他は練習用のみ",
            "officialTestLangsAndOthers" to "およびその他",
            "officialTestLangsUnknown" to "マニュアルに記載なし — {agency}にお問い合わせください",
            "officialTestPracticeNote" to "このアプリでは公式テスト以外の言語でも練習できます。",
        ),
        "es" to mapOf(
            "appTitle" to "Práctica de Examen de Conducir",
            "selectStateDesc" to "Elige tu estado para empezar a practicar",
            "questionsAvailable" to "{count} preguntas",
            "comingSoon" to "Próximamente",
            "title" to "Examen de Conducir {state}",
            "subtitle" to "Practica para el examen escrito del {agency} de {state_name}.",
            "quizzes" to "Pruebas",
            "avgScore" to "Promedio",
            "passStreak" to "Racha",
            "viewStats" to "Ver Estadísticas",
            "modeRandom" to "Aleatorio",
            "modeRandomDesc" to "Todas las preguntas",
            "modeWeak" to "Puntos Débiles",
            "modeWeakDesc" to "Más falladas",
            "numQuestions" to "Número de preguntas:",
            "startQuiz" to "Comenzar",
            "noWeakSpots" to "Sin puntos débiles aún",
            "next" to "Siguiente",
            "seeResults" to "Ver Resultados",
            "missed" to "Fallada",
            "congratulations" to "¡Felicidades!",
            "keepPracticing" to "¡Sigue Practicando!",
            "resultDetail" to
                "Acertaste {correct} de {total}. Necesitas {pass_pct}% para aprobar el examen del {agency}.",
            "newQuiz" to "Nuevo Examen",
            "reviewMissed" to "Revisar Preguntas Falladas ({count})",
            "perfectScore" to "¡Puntuación Perfecta!",
            "perfectMsg" to "Respondiste correctamente todas las preguntas.",
            "yourAnswer" to "Tu respuesta",
            "correct" to "Correcta",
            "back" to "Volver",
            "changeState" to "Cambiar Estado",
            "yourProgress" to "Tu Progreso",
            "qsSeen" to "Vistas",
            "bestScore" to "Mejor",
            "scoreHistory" to "Historial de Puntuación",
            "accuracyByCategory" to "Precisión por Categoría",
            "mostMissed" to "Preguntas Más Falladas",
            "resetAll" to "Borrar Todo el Progreso",
            "resetConfirm" to "Esto borrará todo tu historial y seguimiento de {state_name}. ¿Continuar?",
            "pass" to "APROBADO",
            "fail" to "REPROBADO",
            "passingScore" to "Examen real: {test_count} preguntas, {pass_count} correctas para aprobar ({pass_pct}%)",
            "statsEmpty" to "Toma un examen para ver tu progreso",
            "statsOneMore" to "Toma un examen más para ver el gráfico",
            "cancel" to "Cancelar",
            "resetButton" to "Restablecer",
            "all" to "Todos",
            "aboutThisTest" to "Acerca de este examen",
            "sourceLabel" to "Fuente",
            "editionLabel" to "Edición",
            "fromManual" to "Del manual",
            "fromManualEnNote" to "(en inglés)",
            "cat_license_system" to "Sistema de licencias",
            "cat_driver_testing" to "Exámenes de manejo",
            "cat_driver_responsibility" to "Responsabilidad del conductor",
            "cat_safe_driving_rules" to "Reglas de manejo seguro",
            "cat_defensive_driving" to "Manejo defensivo",
            "cat_alcohol_drugs_health" to "Alcohol, drogas y salud",
            "cat_penalties_and_points" to "Multas y puntos",
            "cat_sharing_the_road" to "Compartir el camino",
            "cat_vehicle_information" to "Información del vehículo",
            "cat_signs_and_signals" to "Señales y semáforos",
            "gradeLabel" to "Grado",
            "fidelityLabel" to "fidelidad",
            "coverageLabel" to "cobertura",
            "officialTestLangsLabel" to "Idiomas del examen oficial",
            "officialTestCaption" to
                "✓ = disponible en el examen oficial del {agency} — los demás son solo para práctica",
            "officialTestLangsAndOthers" to "y otros",
            "officialTestLangsUnknown" to "No indicado en el manual — consulte con {agency}",
            "officialTestPracticeNote" to
                "Esta app también permite practicar en idiomas no disponibles en el examen oficial.",
        ),
        "fr" to mapOf(
            "appTitle" to "Pratique d'examen de conduite",
            "selectStateDesc" to "Choisissez votre province pour commencer",
            "questionsAvailable" to "{count} questions",
            "comingSoon" to "Bientôt disponible",
            "title" to "Examen de conduite {state}",
            "subtitle" to "Pratiquez pour l'examen écrit de {state_name}.",
            "quizzes" to "Tests",
            "avgScore" to "Moyenne",
            "passStreak" to "Série",
            "viewStats" to "Voir les stats",
            "modeRandom" to "Aléatoire",
            "modeRandomDesc" to "Toutes les questions",
            "modeWeak" to "Points faibles",
            "modeWeakDesc" to "Les plus ratées",
            "numQuestions" to "Nombre de questions :",
            "startQuiz" to "Commencer",
            "noWeakSpots" to "Aucun point faible",
            "next" to "Suivant",
            "seeResults" to "Voir les résultats",
            "missed" to "Ratée",
            "congratulations" to "Félicitations !",
            "keepPracticing" to "Continuez à pratiquer !",
            "resultDetail" to "Vous avez obtenu {correct} sur {total}. Il faut {pass_pct}% pour réussir l'examen.",
            "newQuiz" to "Nouveau test",
            "reviewMissed" to "Revoir les erreurs ({count})",
            "perfectScore" to "Score parfait !",
            "perfectMsg" to "Vous avez répondu correctement à toutes les questions.",
            "yourAnswer" to "Votre réponse",
            "correct" to "Correcte",
            "back" to "Retour",
            "changeState" to "Changer de province",
            "yourProgress" to "Votre progrès",
            "qsSeen" to "Vues",
            "bestScore" to "Meilleur",
            "scoreHistory" to "Historique des scores",
            "accuracyByCategory" to "Précision par catégorie",
            "mostMissed" to "Questions les plus ratées",
            "resetAll" to "Effacer tout le progrès",
            "resetConfirm" to "Cela effacera tout votre historique pour {state_name}. Continuer ?",
            "pass" to "RÉUSSI",
            "fail" to "ÉCHOUÉ",
            "passingScore" to
                "Examen réel : {test_count} questions, {pass_count} bonnes réponses pour réussir ({pass_pct}%)",
            "statsEmpty" to "Passez un quiz pour voir votre progression",
            "statsOneMore" to "Passez un quiz de plus pour voir le graphique",
            "cancel" to "Annuler",
            "resetButton" to "Réinitialiser",
            "all" to "Tout",
            "aboutThisTest" to "A propos de cet examen",
            "sourceLabel" to "Source",
            "editionLabel" to "Edition",
            "fromManual" to "Du manuel",
            "fromManualEnNote" to "(en anglais)",
            "cat_license_system" to "Système de permis",
            "cat_driver_testing" to "Examens de conduite",
            "cat_driver_responsibility" to "Responsabilité du conducteur",
            "cat_safe_driving_rules" to "Règles de conduite sûre",
            "cat_defensive_driving" to "Conduite défensive",
            "cat_alcohol_drugs_health" to "Alcool, drogues et santé",
            "cat_penalties_and_points" to "Sanctions et points",
            "cat_sharing_the_road" to "Partage de la route",
            "cat_vehicle_information" to "Informations sur le véhicule",
            "cat_signs_and_signals" to "Panneaux et signaux",
            "gradeLabel" to "Note",
            "fidelityLabel" to "fidélité",
            "coverageLabel" to "couverture",
            "officialTestLangsLabel" to "Langues de l'examen officiel",
            "officialTestCaption" to
                "✓ = proposé à l'examen officiel {agency} — les autres sont pour la pratique uniquement",
            "officialTestLangsAndOthers" to "et autres",
            "officialTestLangsUnknown" to "Non précisé dans le manuel — vérifiez auprès de {agency}",
            "officialTestPracticeNote" to
                "Cette app permet aussi de pratiquer dans des langues non proposées à l'examen officiel.",
        ),
    )

    fun t(
        key: String,
        lang: String,
        vars: Map<String, String> = emptyMap(),
    ): String {
        var s = translations[lang]?.get(key) ?: translations["en"]?.get(key) ?: key
        for ((k, v) in vars) {
            s = s.replace("{$k}", v)
        }
        return s
    }

    fun localizedCategory(
        key: String,
        lang: String,
    ): String {
        val i18nKey = "cat_$key"
        val result = translations[lang]?.get(i18nKey) ?: translations["en"]?.get(i18nKey)
        if (result != null && result != i18nKey) return result
        return key.replace("_", " ").split(" ").joinToString(" ") { word ->
            word.replaceFirstChar { it.uppercase() }
        }
    }

    fun fromManualLabel(lang: String): String {
        val base = t("fromManual", lang)
        val note = t("fromManualEnNote", lang)
        if (note.isEmpty()) return base
        return "$base $note"
    }
}
