import Foundation
import SwiftUI

class Localizer: ObservableObject {
    static let shared = Localizer()

    @Published var currentLang: String {
        didSet { LocalStore.shared.savedLanguage = currentLang }
    }

    let langLabels: [String: String] = ["en": "EN", "ja": "日本語", "es": "ES", "fr": "FR"]

    private var translations: [String: [String: String]] = [:]

    private init() {
        self.currentLang = LocalStore.shared.savedLanguage
        loadTranslations()
    }

    // swiftlint:disable:next function_body_length
    private func loadTranslations() {
        translations = [
            "en": [
                "appTitle": "Driver's Test Practice",
                "selectStateDesc": "Choose your state to start practicing",
                "questionsAvailable": "{count} questions",
                "comingSoon": "Coming soon",
                "title": "{state} Driver's Test",
                "subtitle": "Practice for your {state_name} {agency} written test.",
                "quizzes": "Quizzes",
                "avgScore": "Avg Score",
                "passStreak": "Pass Streak",
                "viewStats": "View Stats",
                "modeRandom": "Random",
                "modeRandomDesc": "All questions",
                "modeWeak": "Weak Spots",
                "modeWeakDesc": "Most missed",
                "numQuestions": "Number of questions:",
                "startQuiz": "Start Quiz",
                "noWeakSpots": "No weak spots yet",
                "next": "Next",
                "seeResults": "See Results",
                "missed": "Missed",
                "congratulations": "Congratulations!",
                "keepPracticing": "Keep Practicing!",
                "resultDetail": "You got {correct} out of {total} correct. You need {pass_pct}% to pass the actual {agency} test.",
                "newQuiz": "New Quiz",
                "reviewMissed": "Review Missed Questions ({count})",
                "perfectScore": "Perfect Score!",
                "perfectMsg": "You answered every question correctly.",
                "yourAnswer": "Your answer",
                "correct": "Correct",
                "back": "Back",
                "changeState": "Change State",
                "yourProgress": "Your Progress",
                "qsSeen": "Q's Seen",
                "bestScore": "Best Score",
                "scoreHistory": "Score History",
                "accuracyByCategory": "Accuracy by Category",
                "mostMissed": "Most Missed Questions",
                "resetAll": "Reset All Progress",
                "resetConfirm": "This will erase all your quiz history and question tracking for {state_name}. Continue?",
                "pass": "PASS",
                "fail": "FAIL",
                "passingScore": "Real test: {test_count} questions, {pass_count} correct to pass ({pass_pct}%)",
                "statsEmpty": "Take a quiz to see your progress",
                "statsOneMore": "Take one more quiz to see the chart",
                "cancel": "Cancel",
                "resetButton": "Reset",
                "all": "All",
                "aboutThisTest": "About this test",
                "source": "Source",
                "edition": "Edition",
                "verified": "Verified",
                "grade": "Grade",
                "fidelity": "Fidelity",
                "coverage": "Coverage",
                "translations": "Translations",
                "questionsInCategory": "questions",
                "fromTheManual": "From the manual",
                "officialTestLangsCaption": "✓ = offered on the official {agency} test — others practice-only",
                "officialTestLangsRow": "Official test languages",
                "officialTestLangsAndOthers": "and others",
                "officialTestLangsNotStated": "Not stated in the manual — check with {agency}",
                "officialTestLangsPractice": "This app offers practice in all available languages regardless of official test language.",
            ],
            "ja": [
                "appTitle": "運転免許テスト練習",
                "selectStateDesc": "練習を開始するには州を選んでください",
                "questionsAvailable": "{count}問",
                "comingSoon": "準備中",
                "title": "{state} 運転免許テスト",
                "subtitle": "{state_name} {agency}の筆記試験対策。",
                "quizzes": "テスト回数",
                "avgScore": "平均点",
                "passStreak": "連続合格",
                "viewStats": "統計を見る",
                "modeRandom": "ランダム",
                "modeRandomDesc": "全問題",
                "modeWeak": "弱点",
                "modeWeakDesc": "よく間違える問題",
                "numQuestions": "問題数：",
                "startQuiz": "テスト開始",
                "noWeakSpots": "弱点はまだありません",
                "next": "次へ",
                "seeResults": "結果を見る",
                "missed": "不正解率",
                "congratulations": "おめでとうございます！",
                "keepPracticing": "もっと練習しましょう！",
                "resultDetail": "{total}問中{correct}問正解です。{agency}試験の合格ラインは{pass_pct}%です。",
                "newQuiz": "新しいテスト",
                "reviewMissed": "間違えた問題を復習 ({count})",
                "perfectScore": "満点！",
                "perfectMsg": "すべての問題に正解しました。",
                "yourAnswer": "あなたの回答",
                "correct": "正解",
                "back": "戻る",
                "changeState": "州を変更",
                "yourProgress": "あなたの成績",
                "qsSeen": "出題済み",
                "bestScore": "最高点",
                "scoreHistory": "スコア推移",
                "accuracyByCategory": "カテゴリー別正答率",
                "mostMissed": "最もよく間違える問題",
                "resetAll": "すべての記録をリセット",
                "resetConfirm": "{state_name}のすべてのテスト履歴と問題追跡データが消去されます。よろしいですか？",
                "pass": "合格",
                "fail": "不合格",
                "passingScore": "本番: {test_count}問中{pass_count}問正解で合格 ({pass_pct}%)",
                "statsEmpty": "クイズを受けて進捗を確認しましょう",
                "statsOneMore": "もう1つクイズを受けてグラフを見ましょう",
                "cancel": "キャンセル",
                "resetButton": "リセット",
                "all": "全て",
                "aboutThisTest": "このテストについて",
                "source": "出典",
                "edition": "版",
                "verified": "検証済み",
                "grade": "評価",
                "fidelity": "忠実度",
                "coverage": "カバー率",
                "translations": "翻訳",
                "questionsInCategory": "問",
                "fromTheManual": "マニュアルより",
                "officialTestLangsCaption": "✓ = {agency}の公式試験で提供 — その他は練習用",
                "officialTestLangsRow": "公式試験の言語",
                "officialTestLangsAndOthers": "その他",
                "officialTestLangsNotStated": "マニュアルに記載なし — {agency}にお問い合わせください",
                "officialTestLangsPractice": "このアプリは公式試験の言語に関わらず、すべての利用可能な言語で練習できます。",
            ],
            "es": [
                "appTitle": "Práctica de Examen de Conducir",
                "selectStateDesc": "Elige tu estado para empezar a practicar",
                "questionsAvailable": "{count} preguntas",
                "comingSoon": "Próximamente",
                "title": "Examen de Conducir {state}",
                "subtitle": "Practica para el examen escrito del {agency} de {state_name}.",
                "quizzes": "Pruebas",
                "avgScore": "Promedio",
                "passStreak": "Racha",
                "viewStats": "Ver Estadísticas",
                "modeRandom": "Aleatorio",
                "modeRandomDesc": "Todas las preguntas",
                "modeWeak": "Puntos Débiles",
                "modeWeakDesc": "Más falladas",
                "numQuestions": "Número de preguntas:",
                "startQuiz": "Comenzar",
                "noWeakSpots": "Sin puntos débiles aún",
                "next": "Siguiente",
                "seeResults": "Ver Resultados",
                "missed": "Fallada",
                "congratulations": "¡Felicidades!",
                "keepPracticing": "¡Sigue Practicando!",
                "resultDetail": "Acertaste {correct} de {total}. Necesitas {pass_pct}% para aprobar el examen del {agency}.",
                "newQuiz": "Nuevo Examen",
                "reviewMissed": "Revisar Preguntas Falladas ({count})",
                "perfectScore": "¡Puntuación Perfecta!",
                "perfectMsg": "Respondiste correctamente todas las preguntas.",
                "yourAnswer": "Tu respuesta",
                "correct": "Correcta",
                "back": "Volver",
                "changeState": "Cambiar Estado",
                "yourProgress": "Tu Progreso",
                "qsSeen": "Vistas",
                "bestScore": "Mejor",
                "scoreHistory": "Historial de Puntuación",
                "accuracyByCategory": "Precisión por Categoría",
                "mostMissed": "Preguntas Más Falladas",
                "resetAll": "Borrar Todo el Progreso",
                "resetConfirm": "Esto borrará todo tu historial y seguimiento de {state_name}. ¿Continuar?",
                "pass": "APROBADO",
                "fail": "REPROBADO",
                "passingScore": "Examen real: {test_count} preguntas, {pass_count} correctas para aprobar ({pass_pct}%)",
                "statsEmpty": "Toma un examen para ver tu progreso",
                "statsOneMore": "Toma un examen más para ver el gráfico",
                "cancel": "Cancelar",
                "resetButton": "Restablecer",
                "all": "Todos",
                "aboutThisTest": "Sobre este examen",
                "source": "Fuente",
                "edition": "Edicion",
                "verified": "Verificado",
                "grade": "Grado",
                "fidelity": "Fidelidad",
                "coverage": "Cobertura",
                "translations": "Traducciones",
                "questionsInCategory": "preguntas",
                "fromTheManual": "Del manual",
                "officialTestLangsCaption": "✓ = disponible en el examen oficial del {agency} — los demás solo para práctica",
                "officialTestLangsRow": "Idiomas oficiales del examen",
                "officialTestLangsAndOthers": "y otros",
                "officialTestLangsNotStated": "No indicado en el manual — consulte con {agency}",
                "officialTestLangsPractice": "Esta aplicación ofrece práctica en todos los idiomas disponibles sin importar el idioma oficial del examen.",
            ],
            "fr": [
                "appTitle": "Pratique d'examen de conduite",
                "selectStateDesc": "Choisissez votre province pour commencer",
                "questionsAvailable": "{count} questions",
                "comingSoon": "Bientôt disponible",
                "title": "Examen de conduite {state}",
                "subtitle": "Pratiquez pour l'examen écrit de {state_name}.",
                "quizzes": "Tests",
                "avgScore": "Moyenne",
                "passStreak": "Série",
                "viewStats": "Voir les stats",
                "modeRandom": "Aléatoire",
                "modeRandomDesc": "Toutes les questions",
                "modeWeak": "Points faibles",
                "modeWeakDesc": "Les plus ratées",
                "numQuestions": "Nombre de questions :",
                "startQuiz": "Commencer",
                "noWeakSpots": "Aucun point faible",
                "next": "Suivant",
                "seeResults": "Voir les résultats",
                "missed": "Ratée",
                "congratulations": "Félicitations !",
                "keepPracticing": "Continuez à pratiquer !",
                "resultDetail": "Vous avez obtenu {correct} sur {total}. Il faut {pass_pct}% pour réussir l'examen.",
                "newQuiz": "Nouveau test",
                "reviewMissed": "Revoir les erreurs ({count})",
                "perfectScore": "Score parfait !",
                "perfectMsg": "Vous avez répondu correctement à toutes les questions.",
                "yourAnswer": "Votre réponse",
                "correct": "Correcte",
                "back": "Retour",
                "changeState": "Changer de province",
                "yourProgress": "Votre progrès",
                "qsSeen": "Vues",
                "bestScore": "Meilleur",
                "scoreHistory": "Historique des scores",
                "accuracyByCategory": "Précision par catégorie",
                "mostMissed": "Questions les plus ratées",
                "resetAll": "Effacer tout le progrès",
                "resetConfirm": "Cela effacera tout votre historique pour {state_name}. Continuer ?",
                "pass": "RÉUSSI",
                "fail": "ÉCHOUÉ",
                "passingScore": "Examen réel : {test_count} questions, {pass_count} bonnes réponses pour réussir ({pass_pct}%)",
                "statsEmpty": "Passez un test pour voir votre progrès",
                "statsOneMore": "Passez un test de plus pour voir le graphique",
                "cancel": "Annuler",
                "resetButton": "Réinitialiser",
                "all": "Tout",
                "aboutThisTest": "A propos de ce test",
                "source": "Source",
                "edition": "Edition",
                "verified": "Verifie",
                "grade": "Note",
                "fidelity": "Fidelite",
                "coverage": "Couverture",
                "translations": "Traductions",
                "questionsInCategory": "questions",
                "fromTheManual": "Du manuel",
                "officialTestLangsCaption": "✓ = proposé à l'examen officiel de {agency} — les autres pour la pratique uniquement",
                "officialTestLangsRow": "Langues officielles de l'examen",
                "officialTestLangsAndOthers": "et autres",
                "officialTestLangsNotStated": "Non précisé dans le manuel — contactez {agency}",
                "officialTestLangsPractice": "Cette application propose la pratique dans toutes les langues disponibles, quel que soit la langue officielle de l'examen.",
            ],
        ]
    }

    func localized(_ key: String, substitutions: [String: String] = [:]) -> String {
        var s = translations[currentLang]?[key] ?? translations["en"]?[key] ?? key
        for (k, v) in substitutions {
            s = s.replacingOccurrences(of: "{\(k)}", with: v)
        }
        return s
    }
}
